ERROR 2024-04-12 18:11:05,205 log 6748 1948 Internal Server Error: /download-from-crossref-api/
Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step1\crossref_api.py", line 178, in download_from_crossref_api
    save_files(article_dois, headers, api)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step1\crossref_api.py", line 143, in save_files
    zip_folder(settings.CROSSREF_ROOT, path)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step1\crossref_api.py", line 49, in zip_folder
    with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
  File "C:\Users\prasenjit\AppData\Local\Programs\Python\Python310\lib\zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\NAL-USDA\\NAL_LIBRARY_SYSTEM\\article_library\\CROSSREF\\2024-04-12.zip'
ERROR 2024-04-12 18:11:05,221 basehttp 6748 1948 "GET /download-from-crossref-api/ HTTP/1.1" 500 133259
ERROR 2024-04-12 20:11:27,102 log 26388 1288 Internal Server Error: /providers-ftp/
Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such column: step1_provider_meta_data_ftp.is_password_required

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\models\query.py", line 398, in __iter__
    self._fetch_all()
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\models\sql\compiler.py", line 1560, in execute_sql
    cursor.execute(sql, params)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such column: step1_provider_meta_data_ftp.is_password_required
ERROR 2024-04-12 20:11:27,102 basehttp 26388 1288 "GET /providers-ftp/ HTTP/1.1" 500 176539
ERROR 2024-04-13 08:15:09,944 log 28716 17368 Internal Server Error: /providers-ftp/
Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such column: step1_provider_meta_data_ftp.email_notification_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\models\query.py", line 398, in __iter__
    self._fetch_all()
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\models\sql\compiler.py", line 1560, in execute_sql
    cursor.execute(sql, params)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such column: step1_provider_meta_data_ftp.email_notification_id
ERROR 2024-04-13 08:15:09,965 basehttp 28716 17368 "GET /providers-ftp/ HTTP/1.1" 500 177369
ERROR 2024-04-13 08:17:01,142 log 28716 17368 Internal Server Error: /providers-ftp/
Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such column: step1_provider_meta_data_ftp.email_notification_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\models\query.py", line 398, in __iter__
    self._fetch_all()
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\models\sql\compiler.py", line 1560, in execute_sql
    cursor.execute(sql, params)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such column: step1_provider_meta_data_ftp.email_notification_id
ERROR 2024-04-13 08:17:01,158 basehttp 28716 17368 "GET /providers-ftp/ HTTP/1.1" 500 177218
ERROR 2024-04-13 08:17:06,161 log 28716 17368 Internal Server Error: /providers-ftp/
Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such column: step1_provider_meta_data_ftp.email_notification_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\models\query.py", line 398, in __iter__
    self._fetch_all()
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\models\sql\compiler.py", line 1560, in execute_sql
    cursor.execute(sql, params)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such column: step1_provider_meta_data_ftp.email_notification_id
ERROR 2024-04-13 08:17:06,161 basehttp 28716 17368 "GET /providers-ftp/ HTTP/1.1" 500 177218
ERROR 2024-04-17 19:06:39,834 log 27100 20524 Internal Server Error: /download-from-crossref-api/
Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
ERROR 2024-04-17 19:06:39,841 basehttp 27100 20524 "GET /download-from-crossref-api/ HTTP/1.1" 500 83087
ERROR 2024-04-17 19:08:31,801 log 33188 18628 Internal Server Error: /download-from-crossref-api/
Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
ERROR 2024-04-17 19:08:31,805 basehttp 33188 18628 "GET /download-from-crossref-api/ HTTP/1.1" 500 83087
ERROR 2024-04-17 19:08:38,400 log 33188 18628 Internal Server Error: /download-from-crossref-api/
Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
ERROR 2024-04-17 19:08:38,403 basehttp 33188 18628 "GET /download-from-crossref-api/ HTTP/1.1" 500 83087
ERROR 2024-04-17 21:35:19,679 log 25384 15524 Internal Server Error: /step2/download-from-ftp/
Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\unzip_ftp_archive.py", line 63, in jsonify_ftp_zipped_xml_files
    unzip_folders(os.path.join(file_path,files),file_path)
  File "C:\Users\prasenjit\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 143, in join
    genericpath._check_arg_types('join', path, *paths)
  File "C:\Users\prasenjit\AppData\Local\Programs\Python\Python310\lib\genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'list'
ERROR 2024-04-17 21:35:19,679 basehttp 25384 15524 "GET /step2/download-from-ftp/ HTTP/1.1" 500 110115
ERROR 2024-04-17 21:40:12,028 log 16652 26652 Internal Server Error: /step2/download-from-ftp/
Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\unzip_ftp_archive.py", line 64, in jsonify_ftp_zipped_xml_files
    file_path = os.path.join(files, f)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'E:\\NAL-USDA\\NAL_LIBRARY_SYSTEM\\article_library\\CSIRO\\E'
ERROR 2024-04-17 21:40:12,040 basehttp 16652 26652 "GET /step2/download-from-ftp/ HTTP/1.1" 500 101472
ERROR 2024-04-17 21:41:24,648 log 27068 8000 Internal Server Error: /step2/download-from-ftp/
Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\unzip_ftp_archive.py", line 64, in jsonify_ftp_zipped_xml_files
    file_path = os.path.join(zip_file_path, f)
  File "C:\Users\prasenjit\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 104, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not list
ERROR 2024-04-17 21:41:24,648 basehttp 27068 8000 "GET /step2/download-from-ftp/ HTTP/1.1" 500 104914
ERROR 2024-04-17 21:43:11,900 log 9524 33648 Internal Server Error: /step2/download-from-ftp/
Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\unzip_ftp_archive.py", line 65, in jsonify_ftp_zipped_xml_files
    unzip_folders(os.path.join(file_path,files),file_path[:-4])
  File "C:\Users\prasenjit\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 143, in join
    genericpath._check_arg_types('join', path, *paths)
  File "C:\Users\prasenjit\AppData\Local\Programs\Python\Python310\lib\genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'list'
ERROR 2024-04-17 21:43:11,908 basehttp 9524 33648 "GET /step2/download-from-ftp/ HTTP/1.1" 500 110751
ERROR 2024-04-17 21:43:39,615 log 32004 33184 Internal Server Error: /step2/download-from-ftp/
Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\unzip_ftp_archive.py", line 65, in jsonify_ftp_zipped_xml_files
    unzip_folders(os.path.join(file_path,files),file_path[:-4])
  File "C:\Users\prasenjit\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 143, in join
    genericpath._check_arg_types('join', path, *paths)
  File "C:\Users\prasenjit\AppData\Local\Programs\Python\Python310\lib\genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'list'
ERROR 2024-04-17 21:43:39,615 basehttp 32004 33184 "GET /step2/download-from-ftp/ HTTP/1.1" 500 110622
ERROR 2024-04-17 21:58:57,147 log 21832 24480 Internal Server Error: /step2/download-from-ftp/
Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\unzip_ftp_archive.py", line 80, in jsonify_ftp_zipped_xml_files
    xml_to_json(xml_file_path)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\unzip_ftp_archive.py", line 25, in xml_to_json
    tree = ET.parse(xml_file)
  File "C:\Users\prasenjit\AppData\Local\Programs\Python\Python310\lib\xml\etree\ElementTree.py", line 1222, in parse
    tree.parse(source, parser)
  File "C:\Users\prasenjit\AppData\Local\Programs\Python\Python310\lib\xml\etree\ElementTree.py", line 569, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\NAL-USDA\\NAL_LIBRARY_SYSTEM\\article_library\\CSIRO\\AM_35_1.ZIP\\AM11033abs.xml'
ERROR 2024-04-17 21:58:57,147 basehttp 21832 24480 "GET /step2/download-from-ftp/ HTTP/1.1" 500 113878
ERROR 2024-04-17 21:59:56,233 log 32388 26136 Internal Server Error: /step2/download-from-ftp/
Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\unzip_ftp_archive.py", line 74, in jsonify_ftp_zipped_xml_files
    unzip_folders(os.path.join(file_path),file_path[:-4])
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\unzip_ftp_archive.py", line 19, in unzip_folders
    with zipfile.ZipFile(zip_file, 'r') as zip_ref:
  File "C:\Users\prasenjit\AppData\Local\Programs\Python\Python310\lib\zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'E:\\NAL-USDA\\NAL_LIBRARY_SYSTEM\\article_library\\CSIRO\\AM_35_1'
ERROR 2024-04-17 21:59:56,247 basehttp 32388 26136 "GET /step2/download-from-ftp/ HTTP/1.1" 500 110475
ERROR 2024-04-17 22:00:11,602 log 32388 26136 Internal Server Error: /step2/download-from-ftp/
Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\unzip_ftp_archive.py", line 74, in jsonify_ftp_zipped_xml_files
    unzip_folders(os.path.join(file_path),file_path[:-4])
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\unzip_ftp_archive.py", line 19, in unzip_folders
    with zipfile.ZipFile(zip_file, 'r') as zip_ref:
  File "C:\Users\prasenjit\AppData\Local\Programs\Python\Python310\lib\zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'E:\\NAL-USDA\\NAL_LIBRARY_SYSTEM\\article_library\\CSIRO\\AM_35_1'
ERROR 2024-04-17 22:00:11,602 basehttp 32388 26136 "GET /step2/download-from-ftp/ HTTP/1.1" 500 110475
ERROR 2024-04-17 22:00:37,976 log 32388 26136 Internal Server Error: /step2/download-from-ftp/
Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\unzip_ftp_archive.py", line 74, in jsonify_ftp_zipped_xml_files
    unzip_folders(os.path.join(file_path),file_path[:-4])
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\unzip_ftp_archive.py", line 19, in unzip_folders
    with zipfile.ZipFile(zip_file, 'r') as zip_ref:
  File "C:\Users\prasenjit\AppData\Local\Programs\Python\Python310\lib\zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'E:\\NAL-USDA\\NAL_LIBRARY_SYSTEM\\article_library\\CSIRO\\AM_35_1'
ERROR 2024-04-17 22:00:37,977 basehttp 32388 26136 "GET /step2/download-from-ftp/ HTTP/1.1" 500 110980
ERROR 2024-04-17 22:01:14,377 log 33716 22680 Internal Server Error: /step2/download-from-ftp/
Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\unzip_ftp_archive.py", line 75, in jsonify_ftp_zipped_xml_files
    unzip_folders(os.path.join(file_path),file_path[:-4])
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\unzip_ftp_archive.py", line 19, in unzip_folders
    with zipfile.ZipFile(zip_file, 'r') as zip_ref:
  File "C:\Users\prasenjit\AppData\Local\Programs\Python\Python310\lib\zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'E:\\NAL-USDA\\NAL_LIBRARY_SYSTEM\\article_library\\CSIRO\\AM_35_1'
ERROR 2024-04-17 22:01:14,379 basehttp 33716 22680 "GET /step2/download-from-ftp/ HTTP/1.1" 500 110974
ERROR 2024-04-17 22:03:08,864 log 33716 22680 Internal Server Error: /step2/download-from-ftp/
Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\unzip_ftp_archive.py", line 82, in jsonify_ftp_zipped_xml_files
    os.remove(xml_file_path + '.xml')
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'E:\\NAL-USDA\\NAL_LIBRARY_SYSTEM\\article_library\\CSIRO\\AM_35_1\\AM11033abs.xml.xml'
ERROR 2024-04-17 22:03:08,873 basehttp 33716 22680 "GET /step2/download-from-ftp/ HTTP/1.1" 500 102795
ERROR 2024-04-17 22:04:13,644 log 24100 31776 Internal Server Error: /step2/download-from-ftp/
Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\unzip_ftp_archive.py", line 75, in jsonify_ftp_zipped_xml_files
    unzip_folders(os.path.join(file_path),file_path[:-4])
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\unzip_ftp_archive.py", line 19, in unzip_folders
    with zipfile.ZipFile(zip_file, 'r') as zip_ref:
  File "C:\Users\prasenjit\AppData\Local\Programs\Python\Python310\lib\zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'E:\\NAL-USDA\\NAL_LIBRARY_SYSTEM\\article_library\\CSIRO\\AM_35_1'
ERROR 2024-04-17 22:04:13,648 basehttp 24100 31776 "GET /step2/download-from-ftp/ HTTP/1.1" 500 110469
ERROR 2024-04-17 22:05:48,781 log 24100 31776 Internal Server Error: /step2/download-from-ftp/
Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\unzip_ftp_archive.py", line 81, in jsonify_ftp_zipped_xml_files
    xml_to_json(xml_file_path)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\unzip_ftp_archive.py", line 26, in xml_to_json
    tree = ET.parse(xml_file)
  File "C:\Users\prasenjit\AppData\Local\Programs\Python\Python310\lib\xml\etree\ElementTree.py", line 1222, in parse
    tree.parse(source, parser)
  File "C:\Users\prasenjit\AppData\Local\Programs\Python\Python310\lib\xml\etree\ElementTree.py", line 580, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 55, column 113
ERROR 2024-04-17 22:05:48,795 basehttp 24100 31776 "GET /step2/download-from-ftp/ HTTP/1.1" 500 114308
ERROR 2024-04-17 22:06:07,910 log 24100 31776 Internal Server Error: /step2/download-from-ftp/
Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\unzip_ftp_archive.py", line 75, in jsonify_ftp_zipped_xml_files
    unzip_folders(os.path.join(file_path),file_path[:-4])
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\unzip_ftp_archive.py", line 19, in unzip_folders
    with zipfile.ZipFile(zip_file, 'r') as zip_ref:
  File "C:\Users\prasenjit\AppData\Local\Programs\Python\Python310\lib\zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'E:\\NAL-USDA\\NAL_LIBRARY_SYSTEM\\article_library\\CSIRO\\AM_35_2'
ERROR 2024-04-17 22:06:07,910 basehttp 24100 31776 "GET /step2/download-from-ftp/ HTTP/1.1" 500 110444
ERROR 2024-04-17 22:15:52,535 log 9100 21776 Internal Server Error: /step2/download-from-ftp/
Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\unzip_ftp_archive.py", line 81, in jsonify_ftp_zipped_xml_files
    jsonified = xml_to_json(xml_file_path)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\unzip_ftp_archive.py", line 26, in xml_to_json
    tree = ET.parse(xml_file)
  File "C:\Users\prasenjit\AppData\Local\Programs\Python\Python310\lib\xml\etree\ElementTree.py", line 1222, in parse
    tree.parse(source, parser)
  File "C:\Users\prasenjit\AppData\Local\Programs\Python\Python310\lib\xml\etree\ElementTree.py", line 580, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: syntax error: line 3, column 0
ERROR 2024-04-17 22:15:52,549 basehttp 9100 21776 "GET /step2/download-from-ftp/ HTTP/1.1" 500 118277
ERROR 2024-04-17 22:20:01,704 log 32220 28760 Internal Server Error: /step2/download-from-ftp/
Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\unzip_ftp_archive.py", line 76, in jsonify_ftp_zipped_xml_files
    unzip_folders(os.path.join(file_path),file_path[:-4])
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\unzip_ftp_archive.py", line 20, in unzip_folders
    with zipfile.ZipFile(zip_file, 'r') as zip_ref:
  File "C:\Users\prasenjit\AppData\Local\Programs\Python\Python310\lib\zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'E:\\NAL-USDA\\NAL_LIBRARY_SYSTEM\\article_library\\CSIRO\\AM_36_1'
ERROR 2024-04-17 22:20:01,719 basehttp 32220 28760 "GET /step2/download-from-ftp/ HTTP/1.1" 500 110938
ERROR 2024-04-17 22:21:05,350 log 20120 17328 Internal Server Error: /step2/download-from-ftp/
Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\unzip_ftp_archive.py", line 84, in jsonify_ftp_zipped_xml_files
    jsonified = xmltodict.parse(xml_content)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\xmltodict.py", line 372, in parse
    parser.ParseFile(xml_input)
TypeError: read() did not return a bytes object (type=str)
ERROR 2024-04-17 22:21:05,365 basehttp 20120 17328 "GET /step2/download-from-ftp/ HTTP/1.1" 500 108921
ERROR 2024-04-17 22:22:11,089 log 17020 19832 Internal Server Error: /step2/download-from-ftp/
Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\unzip_ftp_archive.py", line 76, in jsonify_ftp_zipped_xml_files
    unzip_folders(os.path.join(file_path),file_path[:-4])
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\unzip_ftp_archive.py", line 20, in unzip_folders
    with zipfile.ZipFile(zip_file, 'r') as zip_ref:
  File "C:\Users\prasenjit\AppData\Local\Programs\Python\Python310\lib\zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'E:\\NAL-USDA\\NAL_LIBRARY_SYSTEM\\article_library\\CSIRO\\AM_35_1'
ERROR 2024-04-17 22:22:11,105 basehttp 17020 19832 "GET /step2/download-from-ftp/ HTTP/1.1" 500 110989
ERROR 2024-04-17 22:22:41,414 log 17020 19832 Internal Server Error: /step2/download-from-ftp/
Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\unzip_ftp_archive.py", line 84, in jsonify_ftp_zipped_xml_files
    jsonified = xmltodict.parse(xml_file_path)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\xmltodict.py", line 378, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 2
ERROR 2024-04-17 22:22:41,421 basehttp 17020 19832 "GET /step2/download-from-ftp/ HTTP/1.1" 500 108737
ERROR 2024-04-17 22:23:13,851 log 21268 6180 Internal Server Error: /step2/download-from-ftp/
Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\unzip_ftp_archive.py", line 76, in jsonify_ftp_zipped_xml_files
    unzip_folders(os.path.join(file_path),file_path[:-4])
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\unzip_ftp_archive.py", line 20, in unzip_folders
    with zipfile.ZipFile(zip_file, 'r') as zip_ref:
  File "C:\Users\prasenjit\AppData\Local\Programs\Python\Python310\lib\zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'E:\\NAL-USDA\\NAL_LIBRARY_SYSTEM\\article_library\\CSIRO\\AM_35_2'
ERROR 2024-04-17 22:23:13,853 basehttp 21268 6180 "GET /step2/download-from-ftp/ HTTP/1.1" 500 110457
ERROR 2024-04-17 22:24:20,059 log 21268 6180 Internal Server Error: /step2/download-from-ftp/
Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\unzip_ftp_archive.py", line 82, in jsonify_ftp_zipped_xml_files
    jsonified = xml_to_json(xml_file_path)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\unzip_ftp_archive.py", line 27, in xml_to_json
    tree = ET.parse(xml_file)
  File "C:\Users\prasenjit\AppData\Local\Programs\Python\Python310\lib\xml\etree\ElementTree.py", line 1222, in parse
    tree.parse(source, parser)
  File "C:\Users\prasenjit\AppData\Local\Programs\Python\Python310\lib\xml\etree\ElementTree.py", line 580, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: syntax error: line 3, column 0
ERROR 2024-04-17 22:24:20,064 basehttp 21268 6180 "GET /step2/download-from-ftp/ HTTP/1.1" 500 118170
ERROR 2024-04-17 22:26:17,623 log 20048 27328 Internal Server Error: /step2/download-from-ftp/
Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\unzip_ftp_archive.py", line 76, in jsonify_ftp_zipped_xml_files
    unzip_folders(os.path.join(file_path),file_path[:-4])
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\unzip_ftp_archive.py", line 20, in unzip_folders
    with zipfile.ZipFile(zip_file, 'r') as zip_ref:
  File "C:\Users\prasenjit\AppData\Local\Programs\Python\Python310\lib\zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'E:\\NAL-USDA\\NAL_LIBRARY_SYSTEM\\article_library\\CSIRO\\AM_36_1'
ERROR 2024-04-17 22:26:17,630 basehttp 20048 27328 "GET /step2/download-from-ftp/ HTTP/1.1" 500 110434
ERROR 2024-04-17 22:26:33,004 log 20048 27328 Internal Server Error: /step2/download-from-ftp/
Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\unzip_ftp_archive.py", line 84, in jsonify_ftp_zipped_xml_files
    jsonified = xmltodict.parse(xml_file_path)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\xmltodict.py", line 378, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 2
ERROR 2024-04-17 22:26:33,019 basehttp 20048 27328 "GET /step2/download-from-ftp/ HTTP/1.1" 500 108199
ERROR 2024-04-17 22:29:56,925 log 3292 15188 Internal Server Error: /step2/download-from-ftp/
Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\unzip_ftp_archive.py", line 87, in jsonify_ftp_zipped_xml_files
    jsonified = xmltodict.parse(xml_file_path)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\xmltodict.py", line 378, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 2
ERROR 2024-04-17 22:29:56,929 basehttp 3292 15188 "GET /step2/download-from-ftp/ HTTP/1.1" 500 108232
ERROR 2024-04-17 22:30:57,871 log 22916 30668 Internal Server Error: /step2/download-from-ftp/
Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\unzip_ftp_archive.py", line 80, in jsonify_ftp_zipped_xml_files
    unzip_folders(os.path.join(file_path),file_path[:-4])
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\unzip_ftp_archive.py", line 21, in unzip_folders
    with zipfile.ZipFile(zip_file, 'r') as zip_ref:
  File "C:\Users\prasenjit\AppData\Local\Programs\Python\Python310\lib\zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'E:\\NAL-USDA\\NAL_LIBRARY_SYSTEM\\article_library\\CSIRO\\AM_37_1'
ERROR 2024-04-17 22:30:57,878 basehttp 22916 30668 "GET /step2/download-from-ftp/ HTTP/1.1" 500 110384
ERROR 2024-04-17 22:31:17,995 log 22916 30668 Internal Server Error: /step2/download-from-ftp/
Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\unzip_ftp_archive.py", line 88, in jsonify_ftp_zipped_xml_files
    jsonified = xmltodict.parse(xml_file_path)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\xmltodict.py", line 378, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 2
ERROR 2024-04-17 22:31:17,995 basehttp 22916 30668 "GET /step2/download-from-ftp/ HTTP/1.1" 500 108332
ERROR 2024-04-17 22:31:55,589 log 1696 26404 Internal Server Error: /step2/download-from-ftp/
Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\unzip_ftp_archive.py", line 86, in jsonify_ftp_zipped_xml_files
    jsonified = xml_to_json(xml_file_path)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\unzip_ftp_archive.py", line 30, in xml_to_json
    tree = etree.fromstring(tree, parser=parser)
  File "src\\lxml\\etree.pyx", line 3287, in lxml.etree.fromstring
  File "src\\lxml\\parser.pxi", line 1988, in lxml.etree._parseMemoryDocument
ValueError: can only parse strings
ERROR 2024-04-17 22:31:55,589 basehttp 1696 26404 "GET /step2/download-from-ftp/ HTTP/1.1" 500 107719
ERROR 2024-04-17 22:33:04,549 log 29564 11764 Internal Server Error: /step2/download-from-ftp/
Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\unzip_ftp_archive.py", line 87, in jsonify_ftp_zipped_xml_files
    jsonified = xml_to_json(xml_file_path)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\unzip_ftp_archive.py", line 31, in xml_to_json
    tree = etree.fromstring(tree, parser=parser)
  File "src\\lxml\\etree.pyx", line 3287, in lxml.etree.fromstring
  File "src\\lxml\\parser.pxi", line 1988, in lxml.etree._parseMemoryDocument
ValueError: can only parse strings
ERROR 2024-04-17 22:33:04,562 basehttp 29564 11764 "GET /step2/download-from-ftp/ HTTP/1.1" 500 107776
ERROR 2024-04-17 22:36:56,794 log 4716 25420 Internal Server Error: /step2/download-from-ftp/
Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\unzip_ftp_archive.py", line 89, in jsonify_ftp_zipped_xml_files
    jsonified = xmltodict.parse(xml_file_path, indent=4)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\xmltodict.py", line 336, in parse
    handler = _DictSAXHandler(namespace_separator=namespace_separator,
TypeError: _DictSAXHandler.__init__() got an unexpected keyword argument 'indent'
ERROR 2024-04-17 22:36:56,794 basehttp 4716 25420 "GET /step2/download-from-ftp/ HTTP/1.1" 500 107907
ERROR 2024-04-17 22:37:30,517 log 14076 19020 Internal Server Error: /step2/download-from-ftp/
Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\unzip_ftp_archive.py", line 89, in jsonify_ftp_zipped_xml_files
    jsonified = xmltodict.parse((xml_file_path), indent=4)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\xmltodict.py", line 336, in parse
    handler = _DictSAXHandler(namespace_separator=namespace_separator,
TypeError: _DictSAXHandler.__init__() got an unexpected keyword argument 'indent'
ERROR 2024-04-17 22:37:30,523 basehttp 14076 19020 "GET /step2/download-from-ftp/ HTTP/1.1" 500 107944
ERROR 2024-04-17 22:38:00,576 log 22888 10444 Internal Server Error: /step2/download-from-ftp/
Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\unzip_ftp_archive.py", line 89, in jsonify_ftp_zipped_xml_files
    jsonified = xmltodict.parse((xml_file_path), indent=4)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\xmltodict.py", line 336, in parse
    handler = _DictSAXHandler(namespace_separator=namespace_separator,
TypeError: _DictSAXHandler.__init__() got an unexpected keyword argument 'indent'
ERROR 2024-04-17 22:38:00,576 basehttp 22888 10444 "GET /step2/download-from-ftp/ HTTP/1.1" 500 108044
ERROR 2024-04-17 22:39:28,732 log 20776 26980 Internal Server Error: /step2/download-from-ftp/
Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\unzip_ftp_archive.py", line 90, in jsonify_ftp_zipped_xml_files
    json_data = json.dumps(xmltodict.parse(xml_file_path), indent=4)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\xmltodict.py", line 378, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 2
ERROR 2024-04-17 22:39:28,732 basehttp 20776 26980 "GET /step2/download-from-ftp/ HTTP/1.1" 500 108565
ERROR 2024-04-17 22:40:30,060 log 29344 22776 Internal Server Error: /step2/download-from-ftp/
Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\unzip_ftp_archive.py", line 90, in jsonify_ftp_zipped_xml_files
    json_data = json.dumps(xmltodict.parse(xml_file_path), indent=4)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\xmltodict.py", line 378, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 2
ERROR 2024-04-17 22:40:30,064 basehttp 29344 22776 "GET /step2/download-from-ftp/ HTTP/1.1" 500 108444
ERROR 2024-04-17 22:43:26,379 log 33296 5192 Internal Server Error: /step2/download-from-ftp/
Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\unzip_ftp_archive.py", line 81, in jsonify_ftp_zipped_xml_files
    unzip_folders(os.path.join(file_path),file_path[:-4])
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\unzip_ftp_archive.py", line 21, in unzip_folders
    with zipfile.ZipFile(zip_file, 'r') as zip_ref:
  File "C:\Users\prasenjit\AppData\Local\Programs\Python\Python310\lib\zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'E:\\NAL-USDA\\NAL_LIBRARY_SYSTEM\\article_library\\CSIRO\\AM_36_1'
ERROR 2024-04-17 22:43:26,387 basehttp 33296 5192 "GET /step2/download-from-ftp/ HTTP/1.1" 500 110434
ERROR 2024-04-17 22:43:41,460 basehttp 33296 5192 "GET /step2/download-from-ftp/ HTTP/1.1" 500 119944
ERROR 2024-04-17 22:44:50,854 basehttp 29384 29000 "GET /step2/download-from-ftp/ HTTP/1.1" 500 120219
ERROR 2024-04-17 22:46:01,383 basehttp 7948 32036 "GET /step2/download-from-ftp/ HTTP/1.1" 500 108601
ERROR 2024-04-17 22:46:22,134 basehttp 4300 24868 "GET /step2/download-from-ftp/ HTTP/1.1" 500 108883
ERROR 2024-04-17 22:46:59,088 basehttp 10484 2420 "GET /step2/download-from-ftp/ HTTP/1.1" 500 108649
ERROR 2024-04-17 22:48:05,516 basehttp 19096 20928 "GET /step2/download-from-ftp/ HTTP/1.1" 500 102780
ERROR 2024-04-17 22:48:52,806 basehttp 31844 32616 "GET /step2/download-from-ftp/ HTTP/1.1" 500 112694
ERROR 2024-04-17 22:49:59,934 basehttp 29864 29424 "GET /step2/download-from-ftp/ HTTP/1.1" 500 111730
ERROR 2024-04-17 22:51:30,041 basehttp 23408 28728 "GET /step2/download-from-ftp/ HTTP/1.1" 500 111747
ERROR 2024-04-17 22:53:09,533 basehttp 33320 33376 "GET /step2/download-from-ftp/ HTTP/1.1" 500 112353
ERROR 2024-04-17 22:54:05,102 basehttp 25096 22036 "GET /step2/download-from-ftp/ HTTP/1.1" 500 112310
